---
- name: Install dependencies for packit_dashboard.
  hosts: all
  vars:
    packit_dashboard_path: /src
  tasks:
    - name: Install all RPM/Python/Node packages needed to run dashboard.
      dnf:
        name:
          - python3-pip
          - python3-flask
          - python3-flask-caching
          - python3-requests
          - npm
          - nss_wrapper
          - python3-mod_wsgi
          - httpd
          - mod_md
          - mod_ssl
          - nss_wrapper
        state: present

    - name: npm install
      npm:
        path: "{{ packit_dashboard_path }}"
